/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BodyGuideRouteImport } from './routes/body-guide'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BookingDoctorIdRouteImport } from './routes/booking/$doctorId'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors/$doctorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyGuideRoute = BodyGuideRouteImport.update({
  id: '/body-guide',
  path: '/body-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingDoctorIdRoute = BookingDoctorIdRouteImport.update({
  id: '/booking/$doctorId',
  path: '/booking/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/body-guide': typeof BodyGuideRoute
  '/search': typeof SearchRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/body-guide': typeof BodyGuideRoute
  '/search': typeof SearchRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/doctors': typeof DoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/body-guide': typeof BodyGuideRoute
  '/search': typeof SearchRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/body-guide'
    | '/search'
    | '/booking/$doctorId'
    | '/doctors/$doctorId'
    | '/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/body-guide'
    | '/search'
    | '/booking/$doctorId'
    | '/doctors/$doctorId'
    | '/doctors'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/body-guide'
    | '/search'
    | '/booking/$doctorId'
    | '/doctors/$doctorId'
    | '/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BodyGuideRoute: typeof BodyGuideRoute
  SearchRoute: typeof SearchRoute
  BookingDoctorIdRoute: typeof BookingDoctorIdRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-guide': {
      id: '/body-guide'
      path: '/body-guide'
      fullPath: '/body-guide'
      preLoaderRoute: typeof BodyGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$doctorId': {
      id: '/booking/$doctorId'
      path: '/booking/$doctorId'
      fullPath: '/booking/$doctorId'
      preLoaderRoute: typeof BookingDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BodyGuideRoute: BodyGuideRoute,
  SearchRoute: SearchRoute,
  BookingDoctorIdRoute: BookingDoctorIdRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
